#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

HOME=$OPENSHIFT_DATA_DIR
PROJECT=$OPENSHIFT_REPO_DIR
NPM=$HOME/node_modules/.bin/npm

# Installing backend dependences
cd $PROJECT/php/application/helpers
composer install

# Installing front-end dependencies
cd $PROJECT/php/static
$NPM install

# Link back uploaded photos in static to the persistent storage of openshift
# because on each deploy, this directory doesn't exist. We need to persist it.
cd $PROJECT/php/static
ln -s $OPENSHIFT_DATA_DIR/uploaded_photos uploaded_photos