#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

HOME=$OPENSHIFT_DATA_DIR
PROJECT=$OPENSHIFT_REPO_DIR
NPM=$HOME/node_modules/.bin/npm

cd $PROJECT/php/static
$NPM install
